### ISSUE TITLE
The sector amount is not behaving in the intended way

### ISSUE THREAD

**Issue by Robson** [nik282000/sectors#1]
Currently on [line 34](https://github.com/nik282000/sectors/blob/master/sectors_1c.pde#L34) we have this:

`for(int i = 0; i < int(random(0, 100)); i++){ //each pattern has 0-100 sectors with random parameters`

I think the intent here is to pick a random number from 0 to 100 and then generate that amount of sectors. So we would be just as likely to get 25 sectors as 75 sectors.

However, what's actually happening is that each time we iterate this loop we are re-evaluating this part of the code: `int(random(0, 100))`. This means that the amount of sectors will be heavily weighted to be very low, because each time we iterate we are checking `i` against a new random number.

Here's a complete script that can be run in Processing, which has the same issue:

```
int counter = 0;
for (int a = 0; a < int(random(0, 100)); a++)
 counter++;
print(counter);
```

Running that code will almost always output very low numbers, rather than an even distribution across 0-100. Here are 20 results from that code:

> 22 21 12 7 23 7 9 13 10 1 17 10 8 13 2 14 9 10 0 2

Luckily, this issue is very easy to solve*. It can be solved by creating a variable before the loop which stores the random number, then doing the comparison against that variable. Our example code would be changed like so:

```
int counter = 0;
int max = int(random(0, 100));
for (int a = 0; a < max; a++)
 counter++;
print(counter);
```

The first 20 results for this are:

> 44 80 50 60 71 73 11 38 83 7 42 38 80 59 61 87 44 79 60 5

_*Although the graphical results will be different after applying this fix, so you may want to use something like 5-25 instead of 0-100._

**Comment by nik282000** [comment]
Awesome catch, thank you! I was wondering why I was getting so few shapes but forgot about it while troubleshooting other issues.
